export type NavItem = { href: string; label: string };
export type SocialLink = { href: string; label: string; icon: string };
export type Service = { title: string; description: string; focus: string[] };
export type SkillDetail = { name: string; category: string; focus: string; progress: number };
export type Project = {
  id: string;
  title: string;
  slug: string;
  description: string;
  longDescription: string;
  category: string;
  status: string;
  technologies: string[];
  features: string[];
  image: string;
  screenshots: string[];
  githubUrl: string;
  liveUrl: string;
  featured: boolean;
  year: number;
  purpose: string;
  solution: string;
  highlights: string[];
  lessons: string[];
};
export type PersonalInfo = Record<string, unknown>;
export type ProfileDetails = Record<string, unknown>;
export type Experience = Record<string, unknown>;
export type Education = Record<string, unknown>;
export type Language = Record<string, unknown>;
